WEAPONS = [
    "NAILGUN", "BFG", "RAILGUN", "MACHINEGUN", "GRENADE", "SHOTGUN",
    "LIGHTNING", "PLASMA", "CHAINGUN", "OTHER_WEAPON", "HMG",
    "PROXMINE", "ROCKET", "GAUNTLET",
]

MEDALS = [
    "COMBOKILL", "HEADSHOT", "FIRSTFRAG", "IMPRESSIVE", "CAPTURES",
    "QUADGOD", "PERFORATED", "EXCELLENT", "ACCURACY", "DEFENDS",
    "RAMPAGE", "MIDAIR", "REVENGE", "ASSISTS", "HUMILIATION",
    "PERFECT",
]

PICKUPS = [
    "HASTE", "FLIGHT", "RED_ARMOR", "BATTLESUIT", "AMMO",
    "GUARD", "INVIS", "YELLOW_ARMOR", "REGEN", "KAMIKAZE",
    "DOUBLER", "TELEPORTER", "MEDKIT", "MEGA_HEALTH", "GREEN_ARMOR",
    "OTHER_HOLDABLE", "INVULNERABILITY", "ARMOR", "HEALTH",
    "SCOUT", "QUAD", "OTHER_POWERUP", "ARMOR_REGEN", "PORTAL"
]
