import pytest

from quakestats.core.q3toql.parsers.base import (
    Q3LogParserModOsp,
)
from quakestats.core.q3toql.transform import (
    Q3toQL,
)
from quakestats.system.qa import (  # noqa
    _regen_asserts,
)


class TestQ3toQL():
    @pytest.fixture
    def osp_game_1(self, testdata_loader):
        ld = testdata_loader('osp-ffa-1.log')
        raw_data = ld.read()
        parser = Q3LogParserModOsp(raw_data)
        games = list(parser.games())
        yield games[0]

    def test_process(self, osp_game_1):
        tf = Q3toQL()
        game = tf.transform(osp_game_1)

        ql_events = list(game.get_events())
        e = ql_events
        # _regen_asserts(e)
        assert e[0]['TYPE'] == 'MATCH_STARTED'  # noqa
        assert e[0]['DATA']['TIME'] == 19600  # noqa
        assert e[0]['DATA']['WARMUP'] == False  # noqa
        assert e[0]['DATA']['MATCH_GUID'] == '84b6924313d35786dc04603e71e5f6f3'  # noqa
        assert e[0]['DATA']['INSTAGIB'] == 0  # noqa
        assert e[0]['DATA']['FACTORY'] == 'quake3'  # noqa
        assert e[0]['DATA']['FACTORY_TITLE'] == 'quake3'  # noqa
        assert e[0]['DATA']['INFECTED'] == 0  # noqa
        assert e[0]['DATA']['TIME_LIMIT'] == '0'  # noqa
        assert e[0]['DATA']['TRAINING'] == 0  # noqa
        assert e[0]['DATA']['FRAG_LIMIT'] == '20'  # noqa
        assert e[0]['DATA']['CAPTURE_LIMIT'] == '0'  # noqa
        assert e[0]['DATA']['SERVER_TITLE'] == 'noname'  # noqa
        assert e[0]['DATA']['GAME_TYPE'] == 'FFA'  # noqa
        assert e[0]['DATA']['QUADHOG'] == 0  # noqa
        assert e[0]['DATA']['ROUND_LIMIT'] == 0  # noqa
        assert e[0]['DATA']['MERCY_LIMIT'] == 0  # noqa
        assert e[0]['DATA']['SCORE_LIMIT'] == 0  # noqa
        assert e[0]['DATA']['MAP'] == 'ASYLUM'  # noqa
        assert e[1]['TYPE'] == 'PLAYER_CONNECT'  # noqa
        assert e[1]['DATA']['TIME'] == 300  # noqa
        assert e[1]['DATA']['WARMUP'] == False  # noqa
        assert e[1]['DATA']['MATCH_GUID'] == '84b6924313d35786dc04603e71e5f6f3'  # noqa
        assert e[1]['DATA']['NAME'] == 'Bartoszer'  # noqa
        assert e[1]['DATA']['STEAM_ID'] == '6179638dba55b8f5d2da7838'  # noqa
        assert e[2]['TYPE'] == 'PLAYER_SWITCHTEAM'  # noqa
        assert e[2]['DATA']['TIME'] == 300  # noqa
        assert e[2]['DATA']['WARMUP'] == False  # noqa
        assert e[2]['DATA']['MATCH_GUID'] == '84b6924313d35786dc04603e71e5f6f3'  # noqa
        assert e[2]['DATA']['KILLER']['STEAM_ID'] == '6179638dba55b8f5d2da7838'  # noqa
        assert e[2]['DATA']['KILLER']['OLD_TEAM'] == 'SPECTATOR'  # noqa
        assert e[2]['DATA']['KILLER']['TEAM'] == 'FREE'  # noqa
        assert e[2]['DATA']['KILLER']['NAME'] == 'Bartoszer'  # noqa
        assert e[3]['TYPE'] == 'PLAYER_CONNECT'  # noqa
        assert e[3]['DATA']['TIME'] == 300  # noqa
        assert e[3]['DATA']['WARMUP'] == False  # noqa
        assert e[3]['DATA']['MATCH_GUID'] == '84b6924313d35786dc04603e71e5f6f3'  # noqa
        assert e[3]['DATA']['NAME'] == 'Daemia'  # noqa
        assert e[3]['DATA']['STEAM_ID'] == '254e24151c9e5466251073e6'  # noqa
        assert e[4]['TYPE'] == 'PLAYER_SWITCHTEAM'  # noqa
        assert e[4]['DATA']['TIME'] == 300  # noqa
        assert e[4]['DATA']['WARMUP'] == False  # noqa
        assert e[4]['DATA']['MATCH_GUID'] == '84b6924313d35786dc04603e71e5f6f3'  # noqa
        assert e[4]['DATA']['KILLER']['STEAM_ID'] == '254e24151c9e5466251073e6'  # noqa
        assert e[4]['DATA']['KILLER']['OLD_TEAM'] == 'SPECTATOR'  # noqa
        assert e[4]['DATA']['KILLER']['TEAM'] == 'FREE'  # noqa
        assert e[4]['DATA']['KILLER']['NAME'] == 'Daemia'  # noqa
        assert e[5]['TYPE'] == 'PLAYER_CONNECT'  # noqa
        assert e[5]['DATA']['TIME'] == 300  # noqa
        assert e[5]['DATA']['WARMUP'] == False  # noqa
        assert e[5]['DATA']['MATCH_GUID'] == '84b6924313d35786dc04603e71e5f6f3'  # noqa
        assert e[5]['DATA']['NAME'] == 'Doom'  # noqa
        assert e[5]['DATA']['STEAM_ID'] == '7727c59e2bf61c4a67428d15'  # noqa
        assert e[6]['TYPE'] == 'PLAYER_SWITCHTEAM'  # noqa
        assert e[6]['DATA']['TIME'] == 300  # noqa
        assert e[6]['DATA']['WARMUP'] == False  # noqa
        assert e[6]['DATA']['MATCH_GUID'] == '84b6924313d35786dc04603e71e5f6f3'  # noqa
        assert e[6]['DATA']['KILLER']['STEAM_ID'] == '7727c59e2bf61c4a67428d15'  # noqa
        assert e[6]['DATA']['KILLER']['OLD_TEAM'] == 'SPECTATOR'  # noqa
        assert e[6]['DATA']['KILLER']['TEAM'] == 'FREE'  # noqa
        assert e[6]['DATA']['KILLER']['NAME'] == 'Doom'  # noqa
        assert e[7]['TYPE'] == 'PLAYER_STATS'  # noqa
        assert e[7]['DATA']['TIME'] == 315200  # noqa
        assert e[7]['DATA']['WARMUP'] == False  # noqa
        assert e[7]['DATA']['MATCH_GUID'] == '84b6924313d35786dc04603e71e5f6f3'  # noqa
        assert e[7]['DATA']['TIED_TEAM_RANK'] is None  # noqa
        assert e[7]['DATA']['QUIT'] is None  # noqa
        assert e[7]['DATA']['WEAPONS']['NAILGUN']['K'] == 0  # noqa
        assert e[7]['DATA']['WEAPONS']['NAILGUN']['P'] == 0  # noqa
        assert e[7]['DATA']['WEAPONS']['NAILGUN']['DR'] == 0  # noqa
        assert e[7]['DATA']['WEAPONS']['NAILGUN']['H'] == 0  # noqa
        assert e[7]['DATA']['WEAPONS']['NAILGUN']['D'] == 0  # noqa
        assert e[7]['DATA']['WEAPONS']['NAILGUN']['DG'] == 0  # noqa
        assert e[7]['DATA']['WEAPONS']['NAILGUN']['T'] == 0  # noqa
        assert e[7]['DATA']['WEAPONS']['NAILGUN']['S'] == 0  # noqa
        assert e[7]['DATA']['WEAPONS']['BFG']['K'] == 0  # noqa
        assert e[7]['DATA']['WEAPONS']['BFG']['P'] == 0  # noqa
        assert e[7]['DATA']['WEAPONS']['BFG']['DR'] == 0  # noqa
        assert e[7]['DATA']['WEAPONS']['BFG']['H'] == 0  # noqa
        assert e[7]['DATA']['WEAPONS']['BFG']['D'] == 0  # noqa
        assert e[7]['DATA']['WEAPONS']['BFG']['DG'] == 0  # noqa
        assert e[7]['DATA']['WEAPONS']['BFG']['T'] == 0  # noqa
        assert e[7]['DATA']['WEAPONS']['BFG']['S'] == 0  # noqa
        assert e[7]['DATA']['WEAPONS']['RAILGUN']['K'] == 0  # noqa
        assert e[7]['DATA']['WEAPONS']['RAILGUN']['P'] == 0  # noqa
        assert e[7]['DATA']['WEAPONS']['RAILGUN']['DR'] == 0  # noqa
        assert e[7]['DATA']['WEAPONS']['RAILGUN']['H'] == 0  # noqa
        assert e[7]['DATA']['WEAPONS']['RAILGUN']['D'] == 0  # noqa
        assert e[7]['DATA']['WEAPONS']['RAILGUN']['DG'] == 0  # noqa
        assert e[7]['DATA']['WEAPONS']['RAILGUN']['T'] == 0  # noqa
        assert e[7]['DATA']['WEAPONS']['RAILGUN']['S'] == 0  # noqa
        assert e[7]['DATA']['WEAPONS']['MACHINEGUN']['K'] == 0  # noqa
        assert e[7]['DATA']['WEAPONS']['MACHINEGUN']['P'] == 0  # noqa
        assert e[7]['DATA']['WEAPONS']['MACHINEGUN']['DR'] == 0  # noqa
        assert e[7]['DATA']['WEAPONS']['MACHINEGUN']['H'] == 23  # noqa
        assert e[7]['DATA']['WEAPONS']['MACHINEGUN']['D'] == 0  # noqa
        assert e[7]['DATA']['WEAPONS']['MACHINEGUN']['DG'] == 0  # noqa
        assert e[7]['DATA']['WEAPONS']['MACHINEGUN']['T'] == 0  # noqa
        assert e[7]['DATA']['WEAPONS']['MACHINEGUN']['S'] == 152  # noqa
        assert e[7]['DATA']['WEAPONS']['GRENADE']['K'] == 0  # noqa
        assert e[7]['DATA']['WEAPONS']['GRENADE']['P'] == 0  # noqa
        assert e[7]['DATA']['WEAPONS']['GRENADE']['DR'] == 0  # noqa
        assert e[7]['DATA']['WEAPONS']['GRENADE']['H'] == 0  # noqa
        assert e[7]['DATA']['WEAPONS']['GRENADE']['D'] == 0  # noqa
        assert e[7]['DATA']['WEAPONS']['GRENADE']['DG'] == 0  # noqa
        assert e[7]['DATA']['WEAPONS']['GRENADE']['T'] == 0  # noqa
        assert e[7]['DATA']['WEAPONS']['GRENADE']['S'] == 0  # noqa
        assert e[7]['DATA']['WEAPONS']['SHOTGUN']['K'] == 0  # noqa
        assert e[7]['DATA']['WEAPONS']['SHOTGUN']['P'] == 0  # noqa
        assert e[7]['DATA']['WEAPONS']['SHOTGUN']['DR'] == 0  # noqa
        assert e[7]['DATA']['WEAPONS']['SHOTGUN']['H'] == 0  # noqa
        assert e[7]['DATA']['WEAPONS']['SHOTGUN']['D'] == 0  # noqa
        assert e[7]['DATA']['WEAPONS']['SHOTGUN']['DG'] == 0  # noqa
        assert e[7]['DATA']['WEAPONS']['SHOTGUN']['T'] == 0  # noqa
        assert e[7]['DATA']['WEAPONS']['SHOTGUN']['S'] == 0  # noqa
        assert e[7]['DATA']['WEAPONS']['LIGHTNING']['K'] == 0  # noqa
        assert e[7]['DATA']['WEAPONS']['LIGHTNING']['P'] == 0  # noqa
        assert e[7]['DATA']['WEAPONS']['LIGHTNING']['DR'] == 0  # noqa
        assert e[7]['DATA']['WEAPONS']['LIGHTNING']['H'] == 78  # noqa
        assert e[7]['DATA']['WEAPONS']['LIGHTNING']['D'] == 0  # noqa
        assert e[7]['DATA']['WEAPONS']['LIGHTNING']['DG'] == 0  # noqa
        assert e[7]['DATA']['WEAPONS']['LIGHTNING']['T'] == 0  # noqa
        assert e[7]['DATA']['WEAPONS']['LIGHTNING']['S'] == 209  # noqa
        assert e[7]['DATA']['WEAPONS']['PLASMA']['K'] == 0  # noqa
        assert e[7]['DATA']['WEAPONS']['PLASMA']['P'] == 0  # noqa
        assert e[7]['DATA']['WEAPONS']['PLASMA']['DR'] == 0  # noqa
        assert e[7]['DATA']['WEAPONS']['PLASMA']['H'] == 19  # noqa
        assert e[7]['DATA']['WEAPONS']['PLASMA']['D'] == 0  # noqa
        assert e[7]['DATA']['WEAPONS']['PLASMA']['DG'] == 0  # noqa
        assert e[7]['DATA']['WEAPONS']['PLASMA']['T'] == 0  # noqa
        assert e[7]['DATA']['WEAPONS']['PLASMA']['S'] == 126  # noqa
        assert e[7]['DATA']['WEAPONS']['CHAINGUN']['K'] == 0  # noqa
        assert e[7]['DATA']['WEAPONS']['CHAINGUN']['P'] == 0  # noqa
        assert e[7]['DATA']['WEAPONS']['CHAINGUN']['DR'] == 0  # noqa
        assert e[7]['DATA']['WEAPONS']['CHAINGUN']['H'] == 0  # noqa
        assert e[7]['DATA']['WEAPONS']['CHAINGUN']['D'] == 0  # noqa
        assert e[7]['DATA']['WEAPONS']['CHAINGUN']['DG'] == 0  # noqa
        assert e[7]['DATA']['WEAPONS']['CHAINGUN']['T'] == 0  # noqa
        assert e[7]['DATA']['WEAPONS']['CHAINGUN']['S'] == 0  # noqa
        assert e[7]['DATA']['WEAPONS']['OTHER_WEAPON']['K'] == 0  # noqa
        assert e[7]['DATA']['WEAPONS']['OTHER_WEAPON']['P'] == 0  # noqa
        assert e[7]['DATA']['WEAPONS']['OTHER_WEAPON']['DR'] == 0  # noqa
        assert e[7]['DATA']['WEAPONS']['OTHER_WEAPON']['H'] == 0  # noqa
        assert e[7]['DATA']['WEAPONS']['OTHER_WEAPON']['D'] == 0  # noqa
        assert e[7]['DATA']['WEAPONS']['OTHER_WEAPON']['DG'] == 0  # noqa
        assert e[7]['DATA']['WEAPONS']['OTHER_WEAPON']['T'] == 0  # noqa
        assert e[7]['DATA']['WEAPONS']['OTHER_WEAPON']['S'] == 0  # noqa
        assert e[7]['DATA']['WEAPONS']['HMG']['K'] == 0  # noqa
        assert e[7]['DATA']['WEAPONS']['HMG']['P'] == 0  # noqa
        assert e[7]['DATA']['WEAPONS']['HMG']['DR'] == 0  # noqa
        assert e[7]['DATA']['WEAPONS']['HMG']['H'] == 0  # noqa
        assert e[7]['DATA']['WEAPONS']['HMG']['D'] == 0  # noqa
        assert e[7]['DATA']['WEAPONS']['HMG']['DG'] == 0  # noqa
        assert e[7]['DATA']['WEAPONS']['HMG']['T'] == 0  # noqa
        assert e[7]['DATA']['WEAPONS']['HMG']['S'] == 0  # noqa
        assert e[7]['DATA']['WEAPONS']['PROXMINE']['K'] == 0  # noqa
        assert e[7]['DATA']['WEAPONS']['PROXMINE']['P'] == 0  # noqa
        assert e[7]['DATA']['WEAPONS']['PROXMINE']['DR'] == 0  # noqa
        assert e[7]['DATA']['WEAPONS']['PROXMINE']['H'] == 0  # noqa
        assert e[7]['DATA']['WEAPONS']['PROXMINE']['D'] == 0  # noqa
        assert e[7]['DATA']['WEAPONS']['PROXMINE']['DG'] == 0  # noqa
        assert e[7]['DATA']['WEAPONS']['PROXMINE']['T'] == 0  # noqa
        assert e[7]['DATA']['WEAPONS']['PROXMINE']['S'] == 0  # noqa
        assert e[7]['DATA']['WEAPONS']['ROCKET']['K'] == 0  # noqa
        assert e[7]['DATA']['WEAPONS']['ROCKET']['P'] == 0  # noqa
        assert e[7]['DATA']['WEAPONS']['ROCKET']['DR'] == 0  # noqa
        assert e[7]['DATA']['WEAPONS']['ROCKET']['H'] == 18  # noqa
        assert e[7]['DATA']['WEAPONS']['ROCKET']['D'] == 0  # noqa
        assert e[7]['DATA']['WEAPONS']['ROCKET']['DG'] == 0  # noqa
        assert e[7]['DATA']['WEAPONS']['ROCKET']['T'] == 0  # noqa
        assert e[7]['DATA']['WEAPONS']['ROCKET']['S'] == 44  # noqa
        assert e[7]['DATA']['WEAPONS']['GAUNTLET']['K'] == 0  # noqa
        assert e[7]['DATA']['WEAPONS']['GAUNTLET']['P'] == 0  # noqa
        assert e[7]['DATA']['WEAPONS']['GAUNTLET']['DR'] == 0  # noqa
        assert e[7]['DATA']['WEAPONS']['GAUNTLET']['H'] == 8  # noqa
        assert e[7]['DATA']['WEAPONS']['GAUNTLET']['D'] == 0  # noqa
        assert e[7]['DATA']['WEAPONS']['GAUNTLET']['DG'] == 0  # noqa
        assert e[7]['DATA']['WEAPONS']['GAUNTLET']['T'] == 0  # noqa
        assert e[7]['DATA']['WEAPONS']['GAUNTLET']['S'] == 0  # noqa
        assert e[7]['DATA']['MODEL'] is None  # noqa
        assert e[7]['DATA']['PICKUPS']['HASTE'] == 0  # noqa
        assert e[7]['DATA']['PICKUPS']['FLIGHT'] == 0  # noqa
        assert e[7]['DATA']['PICKUPS']['RED_ARMOR'] == 0  # noqa
        assert e[7]['DATA']['PICKUPS']['BATTLESUIT'] == 0  # noqa
        assert e[7]['DATA']['PICKUPS']['AMMO'] == 0  # noqa
        assert e[7]['DATA']['PICKUPS']['GUARD'] == 0  # noqa
        assert e[7]['DATA']['PICKUPS']['INVIS'] == 0  # noqa
        assert e[7]['DATA']['PICKUPS']['YELLOW_ARMOR'] == 0  # noqa
        assert e[7]['DATA']['PICKUPS']['REGEN'] == 0  # noqa
        assert e[7]['DATA']['PICKUPS']['KAMIKAZE'] == 0  # noqa
        assert e[7]['DATA']['PICKUPS']['DOUBLER'] == 0  # noqa
        assert e[7]['DATA']['PICKUPS']['TELEPORTER'] == 0  # noqa
        assert e[7]['DATA']['PICKUPS']['MEDKIT'] == 0  # noqa
        assert e[7]['DATA']['PICKUPS']['MEGA_HEALTH'] == 0  # noqa
        assert e[7]['DATA']['PICKUPS']['GREEN_ARMOR'] == 0  # noqa
        assert e[7]['DATA']['PICKUPS']['OTHER_HOLDABLE'] == 0  # noqa
        assert e[7]['DATA']['PICKUPS']['INVULNERABILITY'] == 0  # noqa
        assert e[7]['DATA']['PICKUPS']['ARMOR'] == 0  # noqa
        assert e[7]['DATA']['PICKUPS']['HEALTH'] == 0  # noqa
        assert e[7]['DATA']['PICKUPS']['SCOUT'] == 0  # noqa
        assert e[7]['DATA']['PICKUPS']['QUAD'] == 0  # noqa
        assert e[7]['DATA']['PICKUPS']['OTHER_POWERUP'] == 0  # noqa
        assert e[7]['DATA']['PICKUPS']['ARMOR_REGEN'] == 0  # noqa
        assert e[7]['DATA']['PICKUPS']['PORTAL'] == 0  # noqa
        assert e[7]['DATA']['LOSE'] == 0  # noqa
        assert e[7]['DATA']['DAMAGE']['DEALT'] == 0  # noqa
        assert e[7]['DATA']['DAMAGE']['TAKEN'] == 0  # noqa
        assert e[7]['DATA']['RED_FLAG_PICKUPS'] == 0  # noqa
        assert e[7]['DATA']['SCORE'] == 0  # noqa
        assert e[7]['DATA']['MAX_STREAK'] == 0  # noqa
        assert e[7]['DATA']['DEATHS'] == 0  # noqa
        assert e[7]['DATA']['PLAY_TIME'] == 0  # noqa
        assert e[7]['DATA']['BLUE_FLAG_PICKUPS'] == 0  # noqa
        assert e[7]['DATA']['NAME'] == 'Bartoszer'  # noqa
        assert e[7]['DATA']['ABORTED'] == False  # noqa
        assert e[7]['DATA']['HOLY_SHITS'] == 0  # noqa
        assert e[7]['DATA']['TEAM_RANK'] is None  # noqa
        assert e[7]['DATA']['KILLS'] == 0  # noqa
        assert e[7]['DATA']['MEDALS']['COMBOKILL'] == 0  # noqa
        assert e[7]['DATA']['MEDALS']['HEADSHOT'] == 0  # noqa
        assert e[7]['DATA']['MEDALS']['FIRSTFRAG'] == 0  # noqa
        assert e[7]['DATA']['MEDALS']['IMPRESSIVE'] == 0  # noqa
        assert e[7]['DATA']['MEDALS']['CAPTURES'] == 0  # noqa
        assert e[7]['DATA']['MEDALS']['QUADGOD'] == 0  # noqa
        assert e[7]['DATA']['MEDALS']['PERFORATED'] == 0  # noqa
        assert e[7]['DATA']['MEDALS']['EXCELLENT'] == 0  # noqa
        assert e[7]['DATA']['MEDALS']['ACCURACY'] == 0  # noqa
        assert e[7]['DATA']['MEDALS']['DEFENDS'] == 0  # noqa
        assert e[7]['DATA']['MEDALS']['RAMPAGE'] == 0  # noqa
        assert e[7]['DATA']['MEDALS']['MIDAIR'] == 0  # noqa
        assert e[7]['DATA']['MEDALS']['REVENGE'] == 0  # noqa
        assert e[7]['DATA']['MEDALS']['ASSISTS'] == 0  # noqa
        assert e[7]['DATA']['MEDALS']['HUMILIATION'] == 0  # noqa
        assert e[7]['DATA']['MEDALS']['PERFECT'] == 0  # noqa
        assert e[7]['DATA']['NEUTRAL_FLAG_PICKUPS'] == 0  # noqa
        assert e[7]['DATA']['TIED_RANK'] is None  # noqa
        assert e[7]['DATA']['WIN'] == 0  # noqa
        assert e[7]['DATA']['TEAM_JOIN_TIME'] == 0  # noqa
        assert e[7]['DATA']['TEAM'] is None  # noqa
        assert e[7]['DATA']['RANK'] == 0  # noqa
        assert e[7]['DATA']['STEAM_ID'] == '6179638dba55b8f5d2da7838'  # noqa
        assert e[8]['TYPE'] == 'PLAYER_STATS'  # noqa
        assert e[8]['DATA']['TIME'] == 315200  # noqa
        assert e[8]['DATA']['WARMUP'] == False  # noqa
        assert e[8]['DATA']['MATCH_GUID'] == '84b6924313d35786dc04603e71e5f6f3'  # noqa
        assert e[8]['DATA']['TIED_TEAM_RANK'] is None  # noqa
        assert e[8]['DATA']['QUIT'] is None  # noqa
        assert e[8]['DATA']['WEAPONS']['NAILGUN']['K'] == 0  # noqa
        assert e[8]['DATA']['WEAPONS']['NAILGUN']['P'] == 0  # noqa
        assert e[8]['DATA']['WEAPONS']['NAILGUN']['DR'] == 0  # noqa
        assert e[8]['DATA']['WEAPONS']['NAILGUN']['H'] == 0  # noqa
        assert e[8]['DATA']['WEAPONS']['NAILGUN']['D'] == 0  # noqa
        assert e[8]['DATA']['WEAPONS']['NAILGUN']['DG'] == 0  # noqa
        assert e[8]['DATA']['WEAPONS']['NAILGUN']['T'] == 0  # noqa
        assert e[8]['DATA']['WEAPONS']['NAILGUN']['S'] == 0  # noqa
        assert e[8]['DATA']['WEAPONS']['BFG']['K'] == 0  # noqa
        assert e[8]['DATA']['WEAPONS']['BFG']['P'] == 0  # noqa
        assert e[8]['DATA']['WEAPONS']['BFG']['DR'] == 0  # noqa
        assert e[8]['DATA']['WEAPONS']['BFG']['H'] == 0  # noqa
        assert e[8]['DATA']['WEAPONS']['BFG']['D'] == 0  # noqa
        assert e[8]['DATA']['WEAPONS']['BFG']['DG'] == 0  # noqa
        assert e[8]['DATA']['WEAPONS']['BFG']['T'] == 0  # noqa
        assert e[8]['DATA']['WEAPONS']['BFG']['S'] == 0  # noqa
        assert e[8]['DATA']['WEAPONS']['RAILGUN']['K'] == 0  # noqa
        assert e[8]['DATA']['WEAPONS']['RAILGUN']['P'] == 0  # noqa
        assert e[8]['DATA']['WEAPONS']['RAILGUN']['DR'] == 0  # noqa
        assert e[8]['DATA']['WEAPONS']['RAILGUN']['H'] == 0  # noqa
        assert e[8]['DATA']['WEAPONS']['RAILGUN']['D'] == 0  # noqa
        assert e[8]['DATA']['WEAPONS']['RAILGUN']['DG'] == 0  # noqa
        assert e[8]['DATA']['WEAPONS']['RAILGUN']['T'] == 0  # noqa
        assert e[8]['DATA']['WEAPONS']['RAILGUN']['S'] == 0  # noqa
        assert e[8]['DATA']['WEAPONS']['MACHINEGUN']['K'] == 0  # noqa
        assert e[8]['DATA']['WEAPONS']['MACHINEGUN']['P'] == 0  # noqa
        assert e[8]['DATA']['WEAPONS']['MACHINEGUN']['DR'] == 0  # noqa
        assert e[8]['DATA']['WEAPONS']['MACHINEGUN']['H'] == 31  # noqa
        assert e[8]['DATA']['WEAPONS']['MACHINEGUN']['D'] == 0  # noqa
        assert e[8]['DATA']['WEAPONS']['MACHINEGUN']['DG'] == 0  # noqa
        assert e[8]['DATA']['WEAPONS']['MACHINEGUN']['T'] == 0  # noqa
        assert e[8]['DATA']['WEAPONS']['MACHINEGUN']['S'] == 136  # noqa
        assert e[8]['DATA']['WEAPONS']['GRENADE']['K'] == 0  # noqa
        assert e[8]['DATA']['WEAPONS']['GRENADE']['P'] == 0  # noqa
        assert e[8]['DATA']['WEAPONS']['GRENADE']['DR'] == 0  # noqa
        assert e[8]['DATA']['WEAPONS']['GRENADE']['H'] == 0  # noqa
        assert e[8]['DATA']['WEAPONS']['GRENADE']['D'] == 0  # noqa
        assert e[8]['DATA']['WEAPONS']['GRENADE']['DG'] == 0  # noqa
        assert e[8]['DATA']['WEAPONS']['GRENADE']['T'] == 0  # noqa
        assert e[8]['DATA']['WEAPONS']['GRENADE']['S'] == 0  # noqa
        assert e[8]['DATA']['WEAPONS']['SHOTGUN']['K'] == 0  # noqa
        assert e[8]['DATA']['WEAPONS']['SHOTGUN']['P'] == 0  # noqa
        assert e[8]['DATA']['WEAPONS']['SHOTGUN']['DR'] == 0  # noqa
        assert e[8]['DATA']['WEAPONS']['SHOTGUN']['H'] == 48  # noqa
        assert e[8]['DATA']['WEAPONS']['SHOTGUN']['D'] == 0  # noqa
        assert e[8]['DATA']['WEAPONS']['SHOTGUN']['DG'] == 0  # noqa
        assert e[8]['DATA']['WEAPONS']['SHOTGUN']['T'] == 0  # noqa
        assert e[8]['DATA']['WEAPONS']['SHOTGUN']['S'] == 330  # noqa
        assert e[8]['DATA']['WEAPONS']['LIGHTNING']['K'] == 0  # noqa
        assert e[8]['DATA']['WEAPONS']['LIGHTNING']['P'] == 0  # noqa
        assert e[8]['DATA']['WEAPONS']['LIGHTNING']['DR'] == 0  # noqa
        assert e[8]['DATA']['WEAPONS']['LIGHTNING']['H'] == 67  # noqa
        assert e[8]['DATA']['WEAPONS']['LIGHTNING']['D'] == 0  # noqa
        assert e[8]['DATA']['WEAPONS']['LIGHTNING']['DG'] == 0  # noqa
        assert e[8]['DATA']['WEAPONS']['LIGHTNING']['T'] == 0  # noqa
        assert e[8]['DATA']['WEAPONS']['LIGHTNING']['S'] == 497  # noqa
        assert e[8]['DATA']['WEAPONS']['PLASMA']['K'] == 0  # noqa
        assert e[8]['DATA']['WEAPONS']['PLASMA']['P'] == 0  # noqa
        assert e[8]['DATA']['WEAPONS']['PLASMA']['DR'] == 0  # noqa
        assert e[8]['DATA']['WEAPONS']['PLASMA']['H'] == 1  # noqa
        assert e[8]['DATA']['WEAPONS']['PLASMA']['D'] == 0  # noqa
        assert e[8]['DATA']['WEAPONS']['PLASMA']['DG'] == 0  # noqa
        assert e[8]['DATA']['WEAPONS']['PLASMA']['T'] == 0  # noqa
        assert e[8]['DATA']['WEAPONS']['PLASMA']['S'] == 10  # noqa
        assert e[8]['DATA']['WEAPONS']['CHAINGUN']['K'] == 0  # noqa
        assert e[8]['DATA']['WEAPONS']['CHAINGUN']['P'] == 0  # noqa
        assert e[8]['DATA']['WEAPONS']['CHAINGUN']['DR'] == 0  # noqa
        assert e[8]['DATA']['WEAPONS']['CHAINGUN']['H'] == 0  # noqa
        assert e[8]['DATA']['WEAPONS']['CHAINGUN']['D'] == 0  # noqa
        assert e[8]['DATA']['WEAPONS']['CHAINGUN']['DG'] == 0  # noqa
        assert e[8]['DATA']['WEAPONS']['CHAINGUN']['T'] == 0  # noqa
        assert e[8]['DATA']['WEAPONS']['CHAINGUN']['S'] == 0  # noqa
        assert e[8]['DATA']['WEAPONS']['OTHER_WEAPON']['K'] == 0  # noqa
        assert e[8]['DATA']['WEAPONS']['OTHER_WEAPON']['P'] == 0  # noqa
        assert e[8]['DATA']['WEAPONS']['OTHER_WEAPON']['DR'] == 0  # noqa
        assert e[8]['DATA']['WEAPONS']['OTHER_WEAPON']['H'] == 0  # noqa
        assert e[8]['DATA']['WEAPONS']['OTHER_WEAPON']['D'] == 0  # noqa
        assert e[8]['DATA']['WEAPONS']['OTHER_WEAPON']['DG'] == 0  # noqa
        assert e[8]['DATA']['WEAPONS']['OTHER_WEAPON']['T'] == 0  # noqa
        assert e[8]['DATA']['WEAPONS']['OTHER_WEAPON']['S'] == 0  # noqa
        assert e[8]['DATA']['WEAPONS']['HMG']['K'] == 0  # noqa
        assert e[8]['DATA']['WEAPONS']['HMG']['P'] == 0  # noqa
        assert e[8]['DATA']['WEAPONS']['HMG']['DR'] == 0  # noqa
        assert e[8]['DATA']['WEAPONS']['HMG']['H'] == 0  # noqa
        assert e[8]['DATA']['WEAPONS']['HMG']['D'] == 0  # noqa
        assert e[8]['DATA']['WEAPONS']['HMG']['DG'] == 0  # noqa
        assert e[8]['DATA']['WEAPONS']['HMG']['T'] == 0  # noqa
        assert e[8]['DATA']['WEAPONS']['HMG']['S'] == 0  # noqa
        assert e[8]['DATA']['WEAPONS']['PROXMINE']['K'] == 0  # noqa
        assert e[8]['DATA']['WEAPONS']['PROXMINE']['P'] == 0  # noqa
        assert e[8]['DATA']['WEAPONS']['PROXMINE']['DR'] == 0  # noqa
        assert e[8]['DATA']['WEAPONS']['PROXMINE']['H'] == 0  # noqa
        assert e[8]['DATA']['WEAPONS']['PROXMINE']['D'] == 0  # noqa
        assert e[8]['DATA']['WEAPONS']['PROXMINE']['DG'] == 0  # noqa
        assert e[8]['DATA']['WEAPONS']['PROXMINE']['T'] == 0  # noqa
        assert e[8]['DATA']['WEAPONS']['PROXMINE']['S'] == 0  # noqa
        assert e[8]['DATA']['WEAPONS']['ROCKET']['K'] == 0  # noqa
        assert e[8]['DATA']['WEAPONS']['ROCKET']['P'] == 0  # noqa
        assert e[8]['DATA']['WEAPONS']['ROCKET']['DR'] == 0  # noqa
        assert e[8]['DATA']['WEAPONS']['ROCKET']['H'] == 9  # noqa
        assert e[8]['DATA']['WEAPONS']['ROCKET']['D'] == 0  # noqa
        assert e[8]['DATA']['WEAPONS']['ROCKET']['DG'] == 0  # noqa
        assert e[8]['DATA']['WEAPONS']['ROCKET']['T'] == 0  # noqa
        assert e[8]['DATA']['WEAPONS']['ROCKET']['S'] == 22  # noqa
        assert e[8]['DATA']['WEAPONS']['GAUNTLET']['K'] == 0  # noqa
        assert e[8]['DATA']['WEAPONS']['GAUNTLET']['P'] == 0  # noqa
        assert e[8]['DATA']['WEAPONS']['GAUNTLET']['DR'] == 0  # noqa
        assert e[8]['DATA']['WEAPONS']['GAUNTLET']['H'] == 0  # noqa
        assert e[8]['DATA']['WEAPONS']['GAUNTLET']['D'] == 0  # noqa
        assert e[8]['DATA']['WEAPONS']['GAUNTLET']['DG'] == 0  # noqa
        assert e[8]['DATA']['WEAPONS']['GAUNTLET']['T'] == 0  # noqa
        assert e[8]['DATA']['WEAPONS']['GAUNTLET']['S'] == 0  # noqa
        assert e[8]['DATA']['MODEL'] is None  # noqa
        assert e[8]['DATA']['PICKUPS']['HASTE'] == 0  # noqa
        assert e[8]['DATA']['PICKUPS']['FLIGHT'] == 0  # noqa
        assert e[8]['DATA']['PICKUPS']['RED_ARMOR'] == 0  # noqa
        assert e[8]['DATA']['PICKUPS']['BATTLESUIT'] == 0  # noqa
        assert e[8]['DATA']['PICKUPS']['AMMO'] == 0  # noqa
        assert e[8]['DATA']['PICKUPS']['GUARD'] == 0  # noqa
        assert e[8]['DATA']['PICKUPS']['INVIS'] == 0  # noqa
        assert e[8]['DATA']['PICKUPS']['YELLOW_ARMOR'] == 0  # noqa
        assert e[8]['DATA']['PICKUPS']['REGEN'] == 0  # noqa
        assert e[8]['DATA']['PICKUPS']['KAMIKAZE'] == 0  # noqa
        assert e[8]['DATA']['PICKUPS']['DOUBLER'] == 0  # noqa
        assert e[8]['DATA']['PICKUPS']['TELEPORTER'] == 0  # noqa
        assert e[8]['DATA']['PICKUPS']['MEDKIT'] == 0  # noqa
        assert e[8]['DATA']['PICKUPS']['MEGA_HEALTH'] == 0  # noqa
        assert e[8]['DATA']['PICKUPS']['GREEN_ARMOR'] == 0  # noqa
        assert e[8]['DATA']['PICKUPS']['OTHER_HOLDABLE'] == 0  # noqa
        assert e[8]['DATA']['PICKUPS']['INVULNERABILITY'] == 0  # noqa
        assert e[8]['DATA']['PICKUPS']['ARMOR'] == 0  # noqa
        assert e[8]['DATA']['PICKUPS']['HEALTH'] == 0  # noqa
        assert e[8]['DATA']['PICKUPS']['SCOUT'] == 0  # noqa
        assert e[8]['DATA']['PICKUPS']['QUAD'] == 0  # noqa
        assert e[8]['DATA']['PICKUPS']['OTHER_POWERUP'] == 0  # noqa
        assert e[8]['DATA']['PICKUPS']['ARMOR_REGEN'] == 0  # noqa
        assert e[8]['DATA']['PICKUPS']['PORTAL'] == 0  # noqa
        assert e[8]['DATA']['LOSE'] == 0  # noqa
        assert e[8]['DATA']['DAMAGE']['DEALT'] == 0  # noqa
        assert e[8]['DATA']['DAMAGE']['TAKEN'] == 0  # noqa
        assert e[8]['DATA']['RED_FLAG_PICKUPS'] == 0  # noqa
        assert e[8]['DATA']['SCORE'] == 0  # noqa
        assert e[8]['DATA']['MAX_STREAK'] == 0  # noqa
        assert e[8]['DATA']['DEATHS'] == 0  # noqa
        assert e[8]['DATA']['PLAY_TIME'] == 0  # noqa
        assert e[8]['DATA']['BLUE_FLAG_PICKUPS'] == 0  # noqa
        assert e[8]['DATA']['NAME'] == 'Daemia'  # noqa
        assert e[8]['DATA']['ABORTED'] == False  # noqa
        assert e[8]['DATA']['HOLY_SHITS'] == 0  # noqa
        assert e[8]['DATA']['TEAM_RANK'] is None  # noqa
        assert e[8]['DATA']['KILLS'] == 0  # noqa
        assert e[8]['DATA']['MEDALS']['COMBOKILL'] == 0  # noqa
        assert e[8]['DATA']['MEDALS']['HEADSHOT'] == 0  # noqa
        assert e[8]['DATA']['MEDALS']['FIRSTFRAG'] == 0  # noqa
        assert e[8]['DATA']['MEDALS']['IMPRESSIVE'] == 0  # noqa
        assert e[8]['DATA']['MEDALS']['CAPTURES'] == 0  # noqa
        assert e[8]['DATA']['MEDALS']['QUADGOD'] == 0  # noqa
        assert e[8]['DATA']['MEDALS']['PERFORATED'] == 0  # noqa
        assert e[8]['DATA']['MEDALS']['EXCELLENT'] == 0  # noqa
        assert e[8]['DATA']['MEDALS']['ACCURACY'] == 0  # noqa
        assert e[8]['DATA']['MEDALS']['DEFENDS'] == 0  # noqa
        assert e[8]['DATA']['MEDALS']['RAMPAGE'] == 0  # noqa
        assert e[8]['DATA']['MEDALS']['MIDAIR'] == 0  # noqa
        assert e[8]['DATA']['MEDALS']['REVENGE'] == 0  # noqa
        assert e[8]['DATA']['MEDALS']['ASSISTS'] == 0  # noqa
        assert e[8]['DATA']['MEDALS']['HUMILIATION'] == 0  # noqa
        assert e[8]['DATA']['MEDALS']['PERFECT'] == 0  # noqa
        assert e[8]['DATA']['NEUTRAL_FLAG_PICKUPS'] == 0  # noqa
        assert e[8]['DATA']['TIED_RANK'] is None  # noqa
        assert e[8]['DATA']['WIN'] == 0  # noqa
        assert e[8]['DATA']['TEAM_JOIN_TIME'] == 0  # noqa
        assert e[8]['DATA']['TEAM'] is None  # noqa
        assert e[8]['DATA']['RANK'] == 0  # noqa
        assert e[8]['DATA']['STEAM_ID'] == '254e24151c9e5466251073e6'  # noqa
        assert e[9]['TYPE'] == 'PLAYER_STATS'  # noqa
        assert e[9]['DATA']['TIME'] == 315200  # noqa
        assert e[9]['DATA']['WARMUP'] == False  # noqa
        assert e[9]['DATA']['MATCH_GUID'] == '84b6924313d35786dc04603e71e5f6f3'  # noqa
        assert e[9]['DATA']['TIED_TEAM_RANK'] is None  # noqa
        assert e[9]['DATA']['QUIT'] is None  # noqa
        assert e[9]['DATA']['WEAPONS']['NAILGUN']['K'] == 0  # noqa
        assert e[9]['DATA']['WEAPONS']['NAILGUN']['P'] == 0  # noqa
        assert e[9]['DATA']['WEAPONS']['NAILGUN']['DR'] == 0  # noqa
        assert e[9]['DATA']['WEAPONS']['NAILGUN']['H'] == 0  # noqa
        assert e[9]['DATA']['WEAPONS']['NAILGUN']['D'] == 0  # noqa
        assert e[9]['DATA']['WEAPONS']['NAILGUN']['DG'] == 0  # noqa
        assert e[9]['DATA']['WEAPONS']['NAILGUN']['T'] == 0  # noqa
        assert e[9]['DATA']['WEAPONS']['NAILGUN']['S'] == 0  # noqa
        assert e[9]['DATA']['WEAPONS']['BFG']['K'] == 0  # noqa
        assert e[9]['DATA']['WEAPONS']['BFG']['P'] == 0  # noqa
        assert e[9]['DATA']['WEAPONS']['BFG']['DR'] == 0  # noqa
        assert e[9]['DATA']['WEAPONS']['BFG']['H'] == 0  # noqa
        assert e[9]['DATA']['WEAPONS']['BFG']['D'] == 0  # noqa
        assert e[9]['DATA']['WEAPONS']['BFG']['DG'] == 0  # noqa
        assert e[9]['DATA']['WEAPONS']['BFG']['T'] == 0  # noqa
        assert e[9]['DATA']['WEAPONS']['BFG']['S'] == 0  # noqa
        assert e[9]['DATA']['WEAPONS']['RAILGUN']['K'] == 0  # noqa
        assert e[9]['DATA']['WEAPONS']['RAILGUN']['P'] == 0  # noqa
        assert e[9]['DATA']['WEAPONS']['RAILGUN']['DR'] == 0  # noqa
        assert e[9]['DATA']['WEAPONS']['RAILGUN']['H'] == 0  # noqa
        assert e[9]['DATA']['WEAPONS']['RAILGUN']['D'] == 0  # noqa
        assert e[9]['DATA']['WEAPONS']['RAILGUN']['DG'] == 0  # noqa
        assert e[9]['DATA']['WEAPONS']['RAILGUN']['T'] == 0  # noqa
        assert e[9]['DATA']['WEAPONS']['RAILGUN']['S'] == 0  # noqa
        assert e[9]['DATA']['WEAPONS']['MACHINEGUN']['K'] == 0  # noqa
        assert e[9]['DATA']['WEAPONS']['MACHINEGUN']['P'] == 0  # noqa
        assert e[9]['DATA']['WEAPONS']['MACHINEGUN']['DR'] == 0  # noqa
        assert e[9]['DATA']['WEAPONS']['MACHINEGUN']['H'] == 30  # noqa
        assert e[9]['DATA']['WEAPONS']['MACHINEGUN']['D'] == 0  # noqa
        assert e[9]['DATA']['WEAPONS']['MACHINEGUN']['DG'] == 0  # noqa
        assert e[9]['DATA']['WEAPONS']['MACHINEGUN']['T'] == 0  # noqa
        assert e[9]['DATA']['WEAPONS']['MACHINEGUN']['S'] == 228  # noqa
        assert e[9]['DATA']['WEAPONS']['GRENADE']['K'] == 0  # noqa
        assert e[9]['DATA']['WEAPONS']['GRENADE']['P'] == 0  # noqa
        assert e[9]['DATA']['WEAPONS']['GRENADE']['DR'] == 0  # noqa
        assert e[9]['DATA']['WEAPONS']['GRENADE']['H'] == 0  # noqa
        assert e[9]['DATA']['WEAPONS']['GRENADE']['D'] == 0  # noqa
        assert e[9]['DATA']['WEAPONS']['GRENADE']['DG'] == 0  # noqa
        assert e[9]['DATA']['WEAPONS']['GRENADE']['T'] == 0  # noqa
        assert e[9]['DATA']['WEAPONS']['GRENADE']['S'] == 0  # noqa
        assert e[9]['DATA']['WEAPONS']['SHOTGUN']['K'] == 0  # noqa
        assert e[9]['DATA']['WEAPONS']['SHOTGUN']['P'] == 0  # noqa
        assert e[9]['DATA']['WEAPONS']['SHOTGUN']['DR'] == 0  # noqa
        assert e[9]['DATA']['WEAPONS']['SHOTGUN']['H'] == 30  # noqa
        assert e[9]['DATA']['WEAPONS']['SHOTGUN']['D'] == 0  # noqa
        assert e[9]['DATA']['WEAPONS']['SHOTGUN']['DG'] == 0  # noqa
        assert e[9]['DATA']['WEAPONS']['SHOTGUN']['T'] == 0  # noqa
        assert e[9]['DATA']['WEAPONS']['SHOTGUN']['S'] == 275  # noqa
        assert e[9]['DATA']['WEAPONS']['LIGHTNING']['K'] == 0  # noqa
        assert e[9]['DATA']['WEAPONS']['LIGHTNING']['P'] == 0  # noqa
        assert e[9]['DATA']['WEAPONS']['LIGHTNING']['DR'] == 0  # noqa
        assert e[9]['DATA']['WEAPONS']['LIGHTNING']['H'] == 26  # noqa
        assert e[9]['DATA']['WEAPONS']['LIGHTNING']['D'] == 0  # noqa
        assert e[9]['DATA']['WEAPONS']['LIGHTNING']['DG'] == 0  # noqa
        assert e[9]['DATA']['WEAPONS']['LIGHTNING']['T'] == 0  # noqa
        assert e[9]['DATA']['WEAPONS']['LIGHTNING']['S'] == 156  # noqa
        assert e[9]['DATA']['WEAPONS']['PLASMA']['K'] == 0  # noqa
        assert e[9]['DATA']['WEAPONS']['PLASMA']['P'] == 0  # noqa
        assert e[9]['DATA']['WEAPONS']['PLASMA']['DR'] == 0  # noqa
        assert e[9]['DATA']['WEAPONS']['PLASMA']['H'] == 2  # noqa
        assert e[9]['DATA']['WEAPONS']['PLASMA']['D'] == 0  # noqa
        assert e[9]['DATA']['WEAPONS']['PLASMA']['DG'] == 0  # noqa
        assert e[9]['DATA']['WEAPONS']['PLASMA']['T'] == 0  # noqa
        assert e[9]['DATA']['WEAPONS']['PLASMA']['S'] == 6  # noqa
        assert e[9]['DATA']['WEAPONS']['CHAINGUN']['K'] == 0  # noqa
        assert e[9]['DATA']['WEAPONS']['CHAINGUN']['P'] == 0  # noqa
        assert e[9]['DATA']['WEAPONS']['CHAINGUN']['DR'] == 0  # noqa
        assert e[9]['DATA']['WEAPONS']['CHAINGUN']['H'] == 0  # noqa
        assert e[9]['DATA']['WEAPONS']['CHAINGUN']['D'] == 0  # noqa
        assert e[9]['DATA']['WEAPONS']['CHAINGUN']['DG'] == 0  # noqa
        assert e[9]['DATA']['WEAPONS']['CHAINGUN']['T'] == 0  # noqa
        assert e[9]['DATA']['WEAPONS']['CHAINGUN']['S'] == 0  # noqa
        assert e[9]['DATA']['WEAPONS']['OTHER_WEAPON']['K'] == 0  # noqa
        assert e[9]['DATA']['WEAPONS']['OTHER_WEAPON']['P'] == 0  # noqa
        assert e[9]['DATA']['WEAPONS']['OTHER_WEAPON']['DR'] == 0  # noqa
        assert e[9]['DATA']['WEAPONS']['OTHER_WEAPON']['H'] == 0  # noqa
        assert e[9]['DATA']['WEAPONS']['OTHER_WEAPON']['D'] == 0  # noqa
        assert e[9]['DATA']['WEAPONS']['OTHER_WEAPON']['DG'] == 0  # noqa
        assert e[9]['DATA']['WEAPONS']['OTHER_WEAPON']['T'] == 0  # noqa
        assert e[9]['DATA']['WEAPONS']['OTHER_WEAPON']['S'] == 0  # noqa
        assert e[9]['DATA']['WEAPONS']['HMG']['K'] == 0  # noqa
        assert e[9]['DATA']['WEAPONS']['HMG']['P'] == 0  # noqa
        assert e[9]['DATA']['WEAPONS']['HMG']['DR'] == 0  # noqa
        assert e[9]['DATA']['WEAPONS']['HMG']['H'] == 0  # noqa
        assert e[9]['DATA']['WEAPONS']['HMG']['D'] == 0  # noqa
        assert e[9]['DATA']['WEAPONS']['HMG']['DG'] == 0  # noqa
        assert e[9]['DATA']['WEAPONS']['HMG']['T'] == 0  # noqa
        assert e[9]['DATA']['WEAPONS']['HMG']['S'] == 0  # noqa
        assert e[9]['DATA']['WEAPONS']['PROXMINE']['K'] == 0  # noqa
        assert e[9]['DATA']['WEAPONS']['PROXMINE']['P'] == 0  # noqa
        assert e[9]['DATA']['WEAPONS']['PROXMINE']['DR'] == 0  # noqa
        assert e[9]['DATA']['WEAPONS']['PROXMINE']['H'] == 0  # noqa
        assert e[9]['DATA']['WEAPONS']['PROXMINE']['D'] == 0  # noqa
        assert e[9]['DATA']['WEAPONS']['PROXMINE']['DG'] == 0  # noqa
        assert e[9]['DATA']['WEAPONS']['PROXMINE']['T'] == 0  # noqa
        assert e[9]['DATA']['WEAPONS']['PROXMINE']['S'] == 0  # noqa
        assert e[9]['DATA']['WEAPONS']['ROCKET']['K'] == 0  # noqa
        assert e[9]['DATA']['WEAPONS']['ROCKET']['P'] == 0  # noqa
        assert e[9]['DATA']['WEAPONS']['ROCKET']['DR'] == 0  # noqa
        assert e[9]['DATA']['WEAPONS']['ROCKET']['H'] == 11  # noqa
        assert e[9]['DATA']['WEAPONS']['ROCKET']['D'] == 0  # noqa
        assert e[9]['DATA']['WEAPONS']['ROCKET']['DG'] == 0  # noqa
        assert e[9]['DATA']['WEAPONS']['ROCKET']['T'] == 0  # noqa
        assert e[9]['DATA']['WEAPONS']['ROCKET']['S'] == 24  # noqa
        assert e[9]['DATA']['WEAPONS']['GAUNTLET']['K'] == 0  # noqa
        assert e[9]['DATA']['WEAPONS']['GAUNTLET']['P'] == 0  # noqa
        assert e[9]['DATA']['WEAPONS']['GAUNTLET']['DR'] == 0  # noqa
        assert e[9]['DATA']['WEAPONS']['GAUNTLET']['H'] == 0  # noqa
        assert e[9]['DATA']['WEAPONS']['GAUNTLET']['D'] == 0  # noqa
        assert e[9]['DATA']['WEAPONS']['GAUNTLET']['DG'] == 0  # noqa
        assert e[9]['DATA']['WEAPONS']['GAUNTLET']['T'] == 0  # noqa
        assert e[9]['DATA']['WEAPONS']['GAUNTLET']['S'] == 0  # noqa
        assert e[9]['DATA']['MODEL'] is None  # noqa
        assert e[9]['DATA']['PICKUPS']['HASTE'] == 0  # noqa
        assert e[9]['DATA']['PICKUPS']['FLIGHT'] == 0  # noqa
        assert e[9]['DATA']['PICKUPS']['RED_ARMOR'] == 0  # noqa
        assert e[9]['DATA']['PICKUPS']['BATTLESUIT'] == 0  # noqa
        assert e[9]['DATA']['PICKUPS']['AMMO'] == 0  # noqa
        assert e[9]['DATA']['PICKUPS']['GUARD'] == 0  # noqa
        assert e[9]['DATA']['PICKUPS']['INVIS'] == 0  # noqa
        assert e[9]['DATA']['PICKUPS']['YELLOW_ARMOR'] == 0  # noqa
        assert e[9]['DATA']['PICKUPS']['REGEN'] == 0  # noqa
        assert e[9]['DATA']['PICKUPS']['KAMIKAZE'] == 0  # noqa
        assert e[9]['DATA']['PICKUPS']['DOUBLER'] == 0  # noqa
        assert e[9]['DATA']['PICKUPS']['TELEPORTER'] == 0  # noqa
        assert e[9]['DATA']['PICKUPS']['MEDKIT'] == 0  # noqa
        assert e[9]['DATA']['PICKUPS']['MEGA_HEALTH'] == 0  # noqa
        assert e[9]['DATA']['PICKUPS']['GREEN_ARMOR'] == 0  # noqa
        assert e[9]['DATA']['PICKUPS']['OTHER_HOLDABLE'] == 0  # noqa
        assert e[9]['DATA']['PICKUPS']['INVULNERABILITY'] == 0  # noqa
        assert e[9]['DATA']['PICKUPS']['ARMOR'] == 0  # noqa
        assert e[9]['DATA']['PICKUPS']['HEALTH'] == 0  # noqa
        assert e[9]['DATA']['PICKUPS']['SCOUT'] == 0  # noqa
        assert e[9]['DATA']['PICKUPS']['QUAD'] == 0  # noqa
        assert e[9]['DATA']['PICKUPS']['OTHER_POWERUP'] == 0  # noqa
        assert e[9]['DATA']['PICKUPS']['ARMOR_REGEN'] == 0  # noqa
        assert e[9]['DATA']['PICKUPS']['PORTAL'] == 0  # noqa
        assert e[9]['DATA']['LOSE'] == 0  # noqa
        assert e[9]['DATA']['DAMAGE']['DEALT'] == 0  # noqa
        assert e[9]['DATA']['DAMAGE']['TAKEN'] == 0  # noqa
        assert e[9]['DATA']['RED_FLAG_PICKUPS'] == 0  # noqa
        assert e[9]['DATA']['SCORE'] == 0  # noqa
        assert e[9]['DATA']['MAX_STREAK'] == 0  # noqa
        assert e[9]['DATA']['DEATHS'] == 0  # noqa
        assert e[9]['DATA']['PLAY_TIME'] == 0  # noqa
        assert e[9]['DATA']['BLUE_FLAG_PICKUPS'] == 0  # noqa
        assert e[9]['DATA']['NAME'] == 'Doom'  # noqa
        assert e[9]['DATA']['ABORTED'] == False  # noqa
        assert e[9]['DATA']['HOLY_SHITS'] == 0  # noqa
        assert e[9]['DATA']['TEAM_RANK'] is None  # noqa
        assert e[9]['DATA']['KILLS'] == 0  # noqa
        assert e[9]['DATA']['MEDALS']['COMBOKILL'] == 0  # noqa
        assert e[9]['DATA']['MEDALS']['HEADSHOT'] == 0  # noqa
        assert e[9]['DATA']['MEDALS']['FIRSTFRAG'] == 0  # noqa
        assert e[9]['DATA']['MEDALS']['IMPRESSIVE'] == 0  # noqa
        assert e[9]['DATA']['MEDALS']['CAPTURES'] == 0  # noqa
        assert e[9]['DATA']['MEDALS']['QUADGOD'] == 0  # noqa
        assert e[9]['DATA']['MEDALS']['PERFORATED'] == 0  # noqa
        assert e[9]['DATA']['MEDALS']['EXCELLENT'] == 0  # noqa
        assert e[9]['DATA']['MEDALS']['ACCURACY'] == 0  # noqa
        assert e[9]['DATA']['MEDALS']['DEFENDS'] == 0  # noqa
        assert e[9]['DATA']['MEDALS']['RAMPAGE'] == 0  # noqa
        assert e[9]['DATA']['MEDALS']['MIDAIR'] == 0  # noqa
        assert e[9]['DATA']['MEDALS']['REVENGE'] == 0  # noqa
        assert e[9]['DATA']['MEDALS']['ASSISTS'] == 0  # noqa
        assert e[9]['DATA']['MEDALS']['HUMILIATION'] == 0  # noqa
        assert e[9]['DATA']['MEDALS']['PERFECT'] == 0  # noqa
        assert e[9]['DATA']['NEUTRAL_FLAG_PICKUPS'] == 0  # noqa
        assert e[9]['DATA']['TIED_RANK'] is None  # noqa
        assert e[9]['DATA']['WIN'] == 0  # noqa
        assert e[9]['DATA']['TEAM_JOIN_TIME'] == 0  # noqa
        assert e[9]['DATA']['TEAM'] is None  # noqa
        assert e[9]['DATA']['RANK'] == 0  # noqa
        assert e[9]['DATA']['STEAM_ID'] == '7727c59e2bf61c4a67428d15'  # noqa
